CREATE TABLE `USERS` (
  `ID` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(255) NULL, 
  `PHONE` VARCHAR(255) NULL,
  `PASSWORD` VARCHAR(255) NULL,
  `FIRST_NAME` VARCHAR(255) NULL,
  `LAST_NAME` VARCHAR(255) NULL,
  `DOB` VARCHAR(255) NULL,
  `CREATED_BY` VARCHAR(50) NULL DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) NULL DEFAULT NULL,
  `CREATED_DATE` DATETIME(6) NULL DEFAULT now(),
  `UPDATED_DATE` DATETIME(6) NULL DEFAULT now(),
  `DELETED` TINYINT(1) NOT NULL DEFAULT 0,
  `VERSION` BIGINT(20) NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  CONSTRAINT email_unique UNIQUE (`EMAIL`)
  );
  
CREATE TABLE `SESSIONS` (
  `ID` VARCHAR(50) NOT NULL,
  `CREATED_BY` VARCHAR(50) NULL DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) NULL DEFAULT NULL,
  `CREATED_DATE` DATETIME(6) NULL DEFAULT now(),
  `UPDATED_DATE` DATETIME(6) NULL DEFAULT now(),
  `DELETED` TINYINT(1) NOT NULL DEFAULT 0,
  `VERSION` BIGINT(20) NULL DEFAULT 1,
  PRIMARY KEY (`ID`));
